PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12


SKILLS_AUTOCOMPLETE_LIMIT = 10
SKILL_NAME_MAX_LENGTH = 124


USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
USER_EMAIL_MAX_LENGTH = 254
USER_PHONE_REGEX = r"^\+7\d{10}$"
USER_PHONE_ALT_REGEX = r"^8\d{10}$"
USER_PHONE_PREFIX = "+7"


PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
PROJECT_DESCRIPTION_MAX_LENGTH = 2000
PROJECT_STATUS_CHOICES = [
    ("open", "Открыт"),
    ("closed", "Закрыт"),
]
PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"


AVATAR_SIZE = (200, 200)
AVATAR_FONT_SIZE = 120
AVATAR_COLORS = [
    (79, 70, 229),
    (5, 150, 105),
    (220, 38, 38),
    (37, 99, 235),
    (202, 138, 4),
    (147, 51, 234),
    (8, 145, 178),
]
AVATAR_UPLOAD_DIR = "avatars/"
DEFAULT_AVATAR = "images/default-avatar.png"

MEDIA_URL = "/media/"
STATIC_URL = "static/"


GITHUB_URL_PATTERN = "github.com"


LANGUAGE_CODE = "ru"
TIME_ZONE = "Asia/Yekaterinburg"